# Generated by Django 4.2 on 2023-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('user_email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
